config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'  # 与controller中的action对应
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :equipments
  resources :rooms do
    resources :seats
  end
  root 'welcome#index' # 将根页面映射到controller中的action
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :seats
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  include Response
  include ExceptionHandler
end

app/controllers/concerns/exception_handler.rb
# 统一定义未找到数据或条目失效时的异常处理方法
module ExceptionHandler
  # provides the more graceful `included` method
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
# 定义返回的格式
module Response
  # 定义json格式的返回
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  before_action :set_equipment, only:[:show, :update, :destroy]
  # TODO 这里不一定，也可以在update和destroy函数中查找？看页面的设计逻辑？还是与页面无关，只看传过来的id参数？

  # GET /equipments
  def index
    # @equipments = Equipment.all
    json_response(Equipment.all)
  end

  # POST /equipments
  def create # 接收post请求并新建设备并存入数据库
    # @equipment = Equipment.new(equipment_params)
    #
    # @equipment.save
    @equipment = Equipment.create!(equipment_params)
    json_response(@equipment, :created)
  end

  # GET /equipments/:id
  def show
    json_response(@equipment)
  end

  # PUT /equipments/:id
  def update
    @equipment.update(equipment_params)
    head :no_content
    # json_response(@equipment, :updated) TODO 可以这么写吗???
  end

  # DELETE /equipments/:id
  def destroy
    @equipment.destroy
    head :no_content
  end

  private
  def equipment_params
    params.require(:equipment).permit(:equipment_number, :allocated_since)
  end

  def set_equipment
    @equipment = Equipment.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only:[:show, :update, :destroy]
  # TODO 这里不一定，也可以在update和destroy函数中查找？看页面的设计逻辑？还是与页面无关，只看传过来的id参数？

  # GET /rooms
  def index
    @rooms = Room.all.order :name
    json_response(@rooms)
  end

  # POST /rooms
  def create # 接收post请求并新建房间并存入数据库
    @room = Room.create!(room_params)
    json_response(@room, :created)
  end

  # GET /rooms/:id
  def show
    json_response(@room)
  end

  # PUT /rooms/:id
  def update
    @room.update(room_params)
    head :no_content
    # json_response(@room, :updated) TODO 可以这么写吗???
  end

  # DELETE /rooms/:id
  def destroy
    @room.destroy
    head :no_content
  end

  private
  def room_params
    params.require(:room).permit(:name, :coords)
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only:[:show, :update, :destroy]

  # GET /seats
  def index
    @seats = Seat.all.order :name
    json_response(@seats)
  end

  # POST /seats
  def create # 接收post请求并新建房间并存入数据库
    @seat = Seat.create!(seat_params)
    json_response(@seat, :created)
  end

  # GET /seats/:id
  def show
    json_response(@seat)
  end

  # PUT /seats/:id
  def update
    @seat.update(seat_params)
    head :no_content
    # json_response(@seat, :updated) TODO 可以这么写吗???
  end

  # DELETE /seats/:id
  def destroy
    @seat.destroy
    head :no_content
  end

  private
  def seat_params
    params.require(:seat).permit(:name, :coords)
  end

  def set_seat
    @seat = Seat.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/equipments/index.html.erb
<h1>实验室设备列表</h1>

<table>
  <tr>
    <th>设备编号</th>
    <th>分配日期</th>
    <th></th>
  </tr>

  <% @equipments.each do |equipment| %>
    <tr>
      <td><%= equipment.equipment_number %></td>
      <td><%= equipment.allocated_since %></td>
      <td><%= link_to '详情', equipment_path(equipment) %></td>
    </tr>
  <% end %>
</table>

app/views/equipments/new.html.erb
<h1>新建/添加实验室设备</h1>

<!--form_with helper，传送含有需要数据的post请求给含有equipments前缀的url-->
<%= form_with scope: :equipment, url: equipments_path, local: true do |form| %> <!--scope接收的参数是单数-->
  <p>
    <%= form.label :设备编号 %><br>
    <%= form.text_field :equipment_number %>
  </p>

  <p>
    <%= form.label :分配自 %><br>
    <%= form.text_area :allocated_since %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/equipments/show.html.erb
<h1>设备编号:</h1><p><%=  @equipment.equipment_number%></p>

<h1>分配自:</h1><p><%=  @equipment.allocated_since%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActAssets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>欢迎来到王越的毕设【实验室资产管理系统】</h1>
<p>项目地址：
  <a href="https://github.com/KellyVV130/act-assets" target="_blank">
    https://github.com/KellyVV130/act-assets
  </a>
</p>